### ISSUE TITLE
Python 3, galaxyproject.galaxy update, and yaml config

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/usegalaxy-playbook#206]
I've updated galaxyproject.galaxy to the latest version and switched Test to use a YAML config. This issue is mainly so that I don't forget a few outstanding issues that I can't work on until next week.

1. See the FIXME comments in 22bac9f3328ac3a81d65c189c267b81aae917454. I haven't run the config playbook on Main but I *think* it should be ok. Remaining issues are due to the yaml conversion.
2. The role can't write Test's uWSGI config properly due to ordering problems, see galaxyproject/ansible-galaxy#66. Test's `galaxy.yml` is currently modified by hand to get it running, don't run the config playbook on Test until this is fixed.
3. Handlers are not running because of galaxyproject/pulsar#172 issue, which will require a pulsar-galaxy-lib release followed by a Galaxy requirements release.

Test's `uwsgi` section for reference:

```yaml
uwsgi:
    # thought I needed this but I don't, error on uwsgi start was due to ordering, not a lack of socket option
    #socket: 127.0.0.1:0
    master: true
    processes: 8
    threads: 4

    single-interpreter: true
    thunder-lock: true
    harakiri: 600
    buffer-size: 16384

    log-maxsize: 134217728
    log-master-bufsize: 15865856

    pythonpath: lib
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app_factory()

    plugins-dir: /cvmfs/test.galaxyproject.org/deps/_conda/envs/_galaxy_/lib/uwsgi/plugins
    plugin: spinningfifo

    zerg: /srv/galaxy/test/var/zergpool.sock

    master-fifo: /srv/galaxy/test/var/zerg-new.fifo
    master-fifo: /srv/galaxy/test/var/zerg-run.fifo
    master-fifo: /srv/galaxy/test/var/zerg-old.fifo

    if-exists: /srv/galaxy/test/var/zerg-run.fifo
    hook-accepting1-once: writefifo:/srv/galaxy/test/var/zerg-run.fifo 2q
    endif:
    hook-accepting1-once: spinningfifo:/srv/galaxy/test/var/zerg-new.fifo 1
```

**TODO**
- [ ] Fix `galaxyproject.galaxy`'s `galaxy_remote_users` and `galaxy_become_users`
- [x] Fix `galaxyproject.galaxy` to write an ordered `uwsgi` section and support uWSGI control blocks
- [x] Pulsar fix for handlers
- [ ] Dynamic options bug fix
- [x] Fix hacking to conda activate
