### ISSUE TITLE
Install & configure Vault on Main; add S3 data source

### ISSUE THREAD

**Issue by dannon** [galaxyproject/usegalaxy-playbook#408]

**Comment by dannon** [comment]
@natefoo  can you help with this?

**Comment by natefoo** [comment]
I have it running on Test, I assume we just need a single service token for Galaxy? Anything else?

**Comment by natefoo** [comment]
I guess we also need a policy? The Galaxy docs don't go into what permissions are needed.

**Comment by afgane** [comment]
Thanks for the update, and the notes.

This is what I have locally in `user_preferences_extra_conf.yml`:
```
preferences:
  aws:
    description: Your AWS API credentials
    inputs:
      - label: Access key
        name: aws_access_key_id
        type: text
        store: vault
      - label: Secret key
        name: aws_secret_access_key
        type: secret
        store: vault
      - label: Bucket name
        name: bucket_name
        type: text
```

and `file_sources_conf.yml`:
```
- type: s3fs
  id: aws_s3
  label: AWS S3
  doc: Your AWS S3 bucket (configure access via the user preferences)
  anon: false
  key: ${user.preferences['aws|aws_access_key_id']}
  secret: ${user.preferences['aws|aws_secret_access_key']}
  bucket: ${user.preferences['aws|bucket_name']}
```
